### ISSUE TITLE
Baritone Crash

### ISSUE THREAD

**Issue by nmsjayden** [0xTas/stardust#5]
This addon crashes when the baritone mod is added. crash report:

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_310.handler$zca000$baritone-meteor$postInit(class_310.java)
	at net.minecraft.class_310.<init>(class_310.java:715)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Linux (amd64) version 6.6.17-01102-gd3cec3c11146
	Java Version: 22, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 44040192 bytes (42 MiB) / 536870912 bytes (512 MiB) up to 1073741824 bytes (1024 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Celeron(R) N4500 @ 1.10GHz
	Identifier: Intel64 Family 6 Model 156 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 1.10
	Number of physical packages: 2
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 1374.88
	Virtual memory used (MB): 994.64
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	Fabric Mods: 
		asteroide: Asteroide 0.1.2
		autoduper: AutoDuper 1.1.1
		automodpack-bootstrap: AutoModpack bootstrap 1.0.0
			automodpack: AutoModpack 4.0.0-beta1
		baritone-meteor: Baritone 1.20.4-SNAPSHOT
			dev_babbaj_nether-pathfinder: nether-pathfinder 1.4.1
		blackout: Blackout 1.0.2
		cipherstoolbox: Cipher's Toolbox 0.1.0
		crystal: Crystal Reborn 1.0.1
		fabric-api: Fabric API 0.97.0+1.20.4
			fabric-api-base: Fabric API Base 0.4.37+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.87+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.5+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.62+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.8+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f
			fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.21+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.20+ee30b13a4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.5+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.56+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f
		fabricloader: Fabric Loader 0.15.10
			mixinextras: MixinExtras 0.3.5
		higtools: HIGTools 2.7.4
		java: Java HotSpot(TM) 64-Bit Server VM 22
		lyra-addon: Lyra Addon 0.7.0
		meteor-additions: MeteorAdditions 1.2.0
			google-chat: GoogleChat 0.7.4
			libjf-base: LibJF Base 3.14.2
			libjf-config-core-v2: LibJF Config 3.14.2
			libjf-translate-v1: LibJF Translate 3.14.2
		meteor-client: Meteor Client 0.5.6-2054
		meteor-crash-addon: Meteor Crash Addon 0.6
		meteor-rejects: Meteor Rejects 0.3
			seedcrackerx-api: SeedCrackerX API 2.10.1
		meteor-villager-roller: Meteor Villager Roller 1.4.4+mc1.20.4-rev.aec87b6
		meteorist: Meteorist 1.8
		meteorplus: Meteor Plus 1.0.8.2
		minecraft: Minecraft 1.20.4
		navine-client: Navine Client 3.2.8
			adventure-platform-fabric: adventure-platform-fabric 5.11.0
				net_kyori_adventure-api: adventure-api 4.15.0
				net_kyori_adventure-key: adventure-key 4.15.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.3.2
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.15.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.15.0
				net_kyori_adventure-text-serializer-ansi: adventure-text-serializer-ansi 4.15.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.15.0
				net_kyori_adventure-text-serializer-json: adventure-text-serializer-json 4.15.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.15.0
				net_kyori_ansi: ansi 1.0.3
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
				net_kyori_option: option 1.0.0
			eu_bycing_net-api-minified: net-api-minified 1.0.0-SNAPSHOT
			org_apache_httpcomponents_httpmime: httpmime 4.5.14
			org_reflections_reflections: reflections 0.10.2
			renderer: Renderer 1.0
			satin: Satin 1.16.0
		numbyhack: Numby Hack 2.2
		orion: Orion 0.2
		reaper: Reaper 0.1
		serverseeker: ServerSeeker 4.3.1
		sodium: Sodium 0.5.8+mc1.20.4
		stardust: Stardust 1.6.1
		streak-addon: TrouserStreak 0.9.2
	Launched Version: 1.20.4
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: virgl (Mesa Intel(R) UHD Graphics (JSL)) GL version 4.3 (Core Profile) Mesa 22.3.6, Mesa/X.org
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	CPU: 2x Intel(R) Celeron(R) N4500 @ 1.10GHz

-- Meteor Client --

Version: 0.5.6
Dev Build: 2054

Chat gpts responce:

It seems like there's an error occurring during the initialization of Minecraft, specifically related to the Baritone mod. The stacktrace indicates that the issue might be stemming from the postInit method of the baritone-meteor module.

One possibility is that there might be a conflict or an issue with the interaction between Baritone and other mods in your setup. It's also possible that there's a bug within the Baritone mod itself.

Here are a few steps you could take to troubleshoot and resolve the issue:

Check for Updates: Ensure that all your mods, including Baritone, are up to date. Sometimes, newer versions contain bug fixes that might resolve your issue.
Mod Compatibility: Check if there are any known compatibility issues between Baritone and other mods you're using. You might need to disable or update conflicting mods.
Error Logs: Look for more detailed error logs, if available. Sometimes, error logs can provide more specific information about the cause of the issue.
Community Forums: Visit forums or communities related to Minecraft modding. Others might have experienced similar issues and could offer solutions or workarounds.
Mod Configuration: Check if there are any configuration options within Baritone that could be causing the problem. Experiment with different settings to see if the issue persists.
Reinstall: If all else fails, try reinstalling Baritone and/or other related mods. Sometimes, a fresh installation can resolve mysterious issues.
Remember to always back up your world and mod configurations before making any significant changes.

**Comment by 0xTas** [comment]
Try the newest dev build of stardust and see if that works.

**Comment by MCdiax** [comment]
works for me

**Comment by 0xTas** [comment]
Assuming this is no longer an issue with the newest dev-builds.
