### ISSUE TITLE
Trying to clear names with stash brander is a nightmare

### ISSUE THREAD

**Issue by WetBonez** [0xTas/stardust#8]
it seems to cycle endlessly, not detect items, and never name things when trying to clear an items name

**Comment by 0xTas** [comment]
What Stardust and Minecraft version is this happening with? Can you confirm that it's happening on one of the [newest dev builds](https://github.com/0xTas/stardust/releases)?

If you haven't already, try increasing the tick-rate slider a bit.

I haven't been able to test yet today, but back when I made the changes linked in your last issue it definitely wasn't doing that for me.

**Comment by 0xTas** [comment]
I'm not able to reproduce this on the latest release, so if you keep encountering the issue on the newest versions (1.7.0 or later), then please open another issue and provide as much additional context as you can.

For example, what type of items are you trying to clear the names of? Is the Rename Prenamed setting enabled? Have you tried adjusting the tick rate slider at all? Are there any errors showing up in your latest.log file? Are you running any other mods or modules which change the way the inventory behaves?
